name: yarn install

on:
  workflow_dispatch:
  workflow_call:

jobs:
  yarn_install:
    name: $ yarn install する
    runs-on: ubuntu-24.04
    steps:
      - name: コードをチェックアウトする
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: $ yarn install する
        run: |
          yarn install --frozen-lockfile
