name: Boilerplate Playwright

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  yarn_install:
    uses: ./.github/workflows/steps/10_yarn_install.yml

  eslint:
    needs: yarn_install
    uses: ./.github/workflows/steps/20_eslint.yml

  yarn_build:
    needs: eslint
    uses: ./.github/workflows/steps/30_yarn_build.yml
