name: Boilerplate Playwright

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  eslint:
    uses: ./.github/workflows/_10_eslint.yml

  yarn_install:
    uses: ./.github/workflows/_10_yarn_install.yml

  yarn_build:
    needs:
      - yarn_install
      - eslint
    uses: ./.github/workflows/_30_yarn_build.yml
